//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaborExchangeEntities : DbContext
    {
        public LaborExchangeEntities()
            : base("name=LaborExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Вакансия> Вакансия { get; set; }
        public virtual DbSet<Контракт> Контракт { get; set; }
        public virtual DbSet<Предприятие> Предприятие { get; set; }
        public virtual DbSet<Специальность> Специальность { get; set; }
        public virtual DbSet<Человек> Человек { get; set; }
        public virtual DbSet<Диплом> Диплом { get; set; }
    }
}
