//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вакансия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вакансия()
        {
            this.Контракт = new HashSet<Контракт>();
        }
    
        public int IDпредприятия { get; set; }
        public int IDспециальности { get; set; }
        public int IDвакансии { get; set; }
        public int Зарплата { get; set; }
        public int КоличествоЧасовВНеделю { get; set; }
    
        public virtual Предприятие Предприятие { get; set; }
        public virtual Специальность Специальность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Контракт> Контракт { get; set; }
    }
}
