//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контракт
    {
        public int IDконтракта { get; set; }
        public int IDвакансии { get; set; }
        public int IDчеловека { get; set; }
        public System.TimeSpan ДатаЗаключения { get; set; }
    
        public virtual Вакансия Вакансия { get; set; }
        public virtual Человек Человек { get; set; }
    }
}
